apiVersion: v1
data:
  POSTGRES_PASSWORD: MXFheTJ3c3g=
  POSTGRES_USER: bm9kZWpz
kind: Secret
metadata:
  labels:
    app: weather-service
    env: prod
    framework: nodejs
  name: database-secrets-7dtgft72ck
type: Opaque
