apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-service
    env: prod
    framework: nodejs
    type: microservice
  name: weather-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-service
      env: prod
      framework: nodejs
  template:
    metadata:
      labels:
        app: weather-service
        env: prod
        framework: nodejs
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: database-configmap-b78hm8dc9b
        - secretRef:
            name: database-secrets-7dtgft72ck
        image: jshaktiraj/go-k8s:0.3.0
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
        name: weather-service
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
