apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-service
    env: prod
    framework: nodejs
    type: microservice
  name: weather-service
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: http
  selector:
    app: weather-service
    env: prod
    framework: nodejs
  sessionAffinity: None
  type: LoadBalancer
